### ISSUE TITLE
关于Mod列表导出

### ISSUE THREAD

**Issue by Qi-Month** [xiaoliziawa/Create-Skyline#1]
栗子可以试试[这个Mod](https://www.mcmod.cn/class/2995.html),这个Mod可以在启动游戏的时候在客户端生成exports/lme_export.json
里面包含了Mod信息

**Comment by xiaoliziawa** [comment]
Very good advice which I have taken on board, thanks!

**Comment by Qi-Month** [comment]
放你妈洋屁😡
