### ISSUE TITLE
补全问题

### ISSUE THREAD

**Issue by 0xarch** [xiaoliziawa/Create-Skyline#14]
没补全写着就像一边吃生啤酒一边喝氰化钾炸鸡

**Comment by xiaoliziawa** [comment]
Sorry, I'm already running commands within the game while using the module Probo JS:
/probejs dump
Exported the file
But VSCode is still not completing my item IDs!

**Comment by xiaoliziawa** [comment]
Sorry, I'm already running commands within the game while using the mod Probo JS:
/probejs dump
Exported the file
But  my VSCode is still not have my item ids.
plz understand

**Comment by 0xarch** [comment]
感觉像是你还没等到你电脑加载出补全来（

**Comment by xiaoliziawa** [comment]
**TS**服务器重启也没有用，我也不知道是什么情况。
之前开发的时候也遇到过同样的问题，**ProbeJS**刚开始还能用，但是后面写着写着就莫名其妙的没有ID补全了。
昨天问了很多人，获得了很多解决办法。今天尝试后对我的VSCode没有任何效果。
 以后写物品ID之类的只能游戏里面输入：**/kjs hand** 来获取。
一些文档可以使用**JSDoc**来进行物品补全。
给你带来了不便，非常抱歉。
