### ISSUE TITLE
关于汉化和资源加载的问题

### ISSUE THREAD

**Issue by Qi-Month** [xiaoliziawa/Create-Skyline#2]
KubeJS 6的资源加载优先级比材质包都低...这边比较建议[这个Mod](https://www.mcmod.cn/class/7734.html)...
参考路径如下..
![image](https://github.com/xiaoliziawa/Create-Skyline/assets/115912382/c66ed8a4-a90f-43b8-9d56-ff050aea427b)

**Comment by xiaoliziawa** [comment]
Sounds like a very good mods, I got it.
